app/asx/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles import views
from django.urls import re_path

from asx import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    url('^django_plotly_dash/', include('django_plotly_dash.urls')),

]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]

app/main/urls.py
from django.urls import path

from .views import IndexView, PriceView

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('price', PriceView.as_view(), name='price'),
]

app/base/models.py
from django.db import models


class BaseRecord(models.Model):
    name = models.CharField(max_length=200, unique=True,
                            help_text="The unique name of this entry")
    description = models.TextField(blank=True, null=True,
                                   help_text="A verbose description of this entry")
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      help_text="The date and time this entry was created at")
    updated_at = models.DateTimeField(auto_now=True,
                                      help_text="The date and time this entry was last updated at")
    removed = models.BooleanField(default=False, db_index=True)

    def get_model_name(self):
        return self.__class__.__name__.lower()

    class Meta:
        abstract = True
        ordering = ['name', ]

app/base/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base/base.html
<!DOCTYPE HTML>
<html>
<head>
    {% load plotly_dash %}
    {% load static %}
    {% block extra_header %}
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
              name='viewport'/>
    {% endblock %}
    {% block app_header_css %}
        <link rel="stylesheet" type="text/css" href="{% static "assets/css/material-kit.min.css" %}"></link>
        <link rel="stylesheet" type="text/css"
              href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    {% endblock %}
    {% plotly_header %}
    <title>Django Plotly Dash Examples - {% block title %}{% endblock %}</title>
</head>
<body class="product-page sidebar-collapse">
<header>
    <nav class="navbar navbar-color-on-scroll   navbar-expand-lg bg-primary"
         id="sectionsNav">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="https://github.com/guidebee/asx_gym">
                    Open AI Australia Stock Exchange(ASX) GYM Env </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="dropdown nav-item">
                        <a href="{% url 'main:index' %}" class=" nav-link">
                            <i class="material-icons">timeline</i> ASX Index
                        </a>

                    </li>
                    <li class="dropdown nav-item">
                        <a href="{% url 'main:price' %}" class=" nav-link">
                            <i class="material-icons">money</i> Stock Price
                        </a>

                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
<main>
    {% block main_top %}{% endblock %}
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-sm-12  ml-auto mr-auto">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</main>
{% block footer %}
    <!--   Core JS Files   -->
    <script src="{% static "assets/js/core/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "assets/js/core/popper.min.js" %}" type="text/javascript"></script>
    <script src="{% static "assets/js/core/bootstrap-material-design.min.js" %}" type="text/javascript"></script>
    <script src="{% static "assets/js/plugins/moment.min.js" %}"></script>
    <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
    <script src="{% static "assets/js/plugins/bootstrap-datetimepicker.js" %}" type="text/javascript"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{% static "assets/js/plugins/nouislider.min.js" %}" type="text/javascript"></script>
    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="{% static "assets/js/plugins/bootstrap-tagsinput.js" %}"></script>
    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="{% static "assets/js/plugins/bootstrap-selectpicker.js" %}" type="text/javascript"></script>
    <!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="{% static "assets/js/plugins/jasny-bootstrap.min.js" %}" type="text/javascript"></script>
    <!--	Plugin for Small Gallery in Product Page -->
    <script src="{% static "assets/js/plugins/jquery.flexisel.js" %}" type="text/javascript"></script>
    <!-- Plugins for presentation and navigation  -->
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Js With initialisations For Demo Purpose, Don't Include it in Your Project -->

    <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
    <script src="{% static "assets/js/material-kit.min.js" %}" type="text/javascript"></script>
{% endblock %}
</body>
{% plotly_footer %}
</html>